# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 148d50c3529976902dd78183e5a1ba380b2e683297a927d098f15feb0188421bfa7cd9a95f46a7542dd0b5d4079753d2460ef7341c57d058eb7082ccea6eec74

test:
  secret_key_base: f26db26ec71c51f978b2c17c5c62b7247773ee7f9a834a94dc621bac49d69e76cbd01ece3964d478e9e86cd58cc0d32ab4d00898fdbaccc70d60d091de9ee774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
